{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}

-- | Pretty-printer for PrintCTT.
--   Generated by the BNF converter.

module PrintCTT where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, dropWhile, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified CoreCTT

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i = \case
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    [";"]        -> showChar ';'
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : ts@(p:_) | closingOrPunctuation p -> showString t . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i     = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t s =
    case (all isSpace t', null spc, null rest) of
      (True , _   , True ) -> []              -- remove trailing space
      (False, _   , True ) -> t'              -- remove trailing space
      (False, True, False) -> t' ++ ' ' : s   -- add space if none
      _                    -> t' ++ s
    where
      t'          = showString t []
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt     _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print CoreCTT.Ident where
  prt _ (CoreCTT.Ident i) = doc $ showString i

instance Print CoreCTT.Program where
  prt i = \case
    CoreCTT.Program decls -> prPrec i 0 (concatD [prt 0 decls])

instance Print CoreCTT.Term where
  prt i = \case
    --CoreCTT.Fun term1 term2 -> prPrec i 0 (concatD [prt 1 term1, doc (showString "->"), prt 0 term2])
    CoreCTT.Abst id_ term1 term2 -> prPrec i 0 (concatD [doc (showString "["), prt 0 id_, doc (showString ":"), prt 0 term1, doc (showString "]"), prt 0 term2])
    CoreCTT.App term1 term2 -> prPrec i 1 (concatD [prt 1 term1, prt 2 term2])
    CoreCTT.Var id_ -> prPrec i 2 (concatD [prt 0 id_])
    CoreCTT.Universe -> prPrec i 2 (concatD [doc (showString "U")])
    CoreCTT.Nat -> prPrec i 2 (concatD [doc (showString "N")])
    CoreCTT.Zero -> prPrec i 2 (concatD [doc (showString "0")])
    CoreCTT.Succ term -> prPrec i 2 (concatD [doc (showString "S"), prt 0 term])
    CoreCTT.Ind term1 term2 term3 term4 -> prPrec i 2 (concatD [prt 0 term1, prt 0 term2,prt 0 term3,prt 0 term4])

instance Print CoreCTT.Toplevel where
  prt i = \case
    CoreCTT.Definition id_ term1 term2 -> prPrec i 0 (concatD [prt 0 id_, doc (showString ":"), prt 0 term1, doc (showString "="), prt 0 term2])
    CoreCTT.Example term -> prPrec i 0 (concatD [prt 0 term])
  prtList _ [] = concatD []
  prtList _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print [CoreCTT.Toplevel] where
  prt = prtList

